# Generated by Django 5.2 on 2025-04-25 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0003_categorymodel_contentmodel_delete_contenblockmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='contentmodel',
            name='views',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
